// ============================================
// HEXSTRIKE AI - CONSTANTS & DATA
// ============================================

export const SITE_CONFIG = {
    name: "HexStrike AI",
    tagline: "The Hacker's Arsenal",
    description: "Elite browser extensions for bug bounty hunters. Transform complex workflows into powerful, streamlined operations.",
    url: "https://hexstrike.ai",
    author: "HexStrike Labs",
    email: "support@hexstrike.ai",
    github: "https://github.com/hexstrike",
    twitter: "@hexstrike_ai",
};

export const CATEGORIES = {
    RECON: {
        name: "Reconnaissance",
        description: "Intelligence gathering and asset discovery",
        icon: "Search",
        color: "cyan",
    },
    ANALYSIS: {
        name: "Analysis",
        description: "Deep inspection and pattern detection",
        icon: "BarChart",
        color: "purple",
    },
    TRACKING: {
        name: "Tracking",
        description: "Monitor and trace application behavior",
        icon: "Target",
        color: "matrix",
    },
    REPORTING: {
        name: "Reporting",
        description: "Document and present findings",
        icon: "FileText",
        color: "orange",
    },
    AUTOMATION: {
        name: "Automation",
        description: "Streamline repetitive workflows",
        icon: "Zap",
        color: "yellow",
    },
    UTILITIES: {
        name: "Utilities",
        description: "Essential tools for every hunter",
        icon: "Tool",
        color: "cyan",
    },
} as const;

export type CategoryKey = keyof typeof CATEGORIES;

export interface Extension {
    id: string;
    slug: string;
    name: string;
    tagline: string;
    description: string;
    features: string[];
    category: CategoryKey;
    price: number;
    salePrice?: number;
    icon: string;
    color: string;
    compatibility: string[];
    version: string;
    featured?: boolean;
}

export const EXTENSIONS: Extension[] = [
    {
        id: "1",
        slug: "js-recon-radar",
        name: "JS Recon Radar",
        tagline: "Deep JavaScript Intelligence Gathering",
        description: "Continuously scans and analyzes JavaScript files to extract endpoints, secrets, API keys, and hidden functionality. Uses advanced static analysis to uncover what others miss.",
        features: [
            "Real-time JS file interception and parsing",
            "Automatic endpoint and API route extraction",
            "Secret and API key detection",
            "Source map analysis for hidden code",
            "Webpack chunk bruteforcing",
            "Ghost endpoint discovery",
        ],
        category: "RECON",
        price: 29.99,
        icon: "📡",
        color: "#00ffff",
        compatibility: ["chrome", "edge"],
        version: "2.1.0",
        featured: true,
    },
    {
        id: "2",
        slug: "paramhawk",
        name: "ParamHawk",
        tagline: "Cross-Page Parameter Tracking & Analysis",
        description: "Tracks every parameter across your entire browsing session. Identifies reflection points, hidden parameters, and potential injection vectors automatically.",
        features: [
            "Cross-page parameter tracking",
            "Automatic reflection detection",
            "Hidden parameter discovery",
            "Parameter mutation testing",
            "Correlation with known vulnerabilities",
            "Export to Burp/ZAP",
        ],
        category: "TRACKING",
        price: 24.99,
        icon: "🦅",
        color: "#8b5cf6",
        compatibility: ["chrome", "edge"],
        version: "1.8.0",
        featured: true,
    },
    {
        id: "3",
        slug: "authflow-visualizer",
        name: "AuthFlow Visualizer",
        tagline: "Authentication Flow Mapping & Diff",
        description: "Automatically builds visual flowcharts of authentication systems. Compare flows between different user roles to identify privilege escalation vectors.",
        features: [
            "Automatic auth flow diagramming",
            "Multi-role flow comparison",
            "Token lifecycle tracking",
            "Session management analysis",
            "OAuth/OIDC flow detection",
            "Misconfiguration alerts",
        ],
        category: "ANALYSIS",
        price: 34.99,
        icon: "🔐",
        color: "#00ff41",
        compatibility: ["chrome", "edge"],
        version: "2.0.0",
        featured: true,
    },
    {
        id: "4",
        slug: "response-anomaly-detector",
        name: "Response Anomaly Detector (RAD)",
        tagline: "Intelligent Response Pattern Analysis",
        description: "Uses pattern recognition to detect anomalies in server responses. Automatically identifies potential vulnerabilities based on response differences.",
        features: [
            "Response fingerprinting",
            "Anomaly pattern detection",
            "Status code analysis",
            "Header comparison",
            "Timing-based detection",
            "Smart alerting system",
        ],
        category: "ANALYSIS",
        price: 29.99,
        icon: "⚡",
        color: "#ff6a00",
        compatibility: ["chrome", "edge"],
        version: "1.5.0",
    },
    {
        id: "5",
        slug: "scope-guardian",
        name: "Scope Guardian + Program Intel Hub",
        tagline: "Program Scope Management & Intelligence",
        description: "Manages your bug bounty program scopes with smart notifications. Aggregates program intelligence from multiple platforms.",
        features: [
            "Multi-program scope management",
            "Real-time scope checking",
            "Out-of-scope alerts",
            "Program intel aggregation",
            "VDP/BBP policy tracking",
            "Scope change notifications",
        ],
        category: "UTILITIES",
        price: 19.99,
        icon: "🛡️",
        color: "#facc15",
        compatibility: ["chrome", "edge"],
        version: "1.3.0",
    },
    {
        id: "6",
        slug: "dom-sink-tracker",
        name: "DOM Sink Tracker",
        tagline: "Real-time DOM Sink Detection",
        description: "Monitors JavaScript execution for dangerous DOM sinks. Tracks data flow from sources to sinks to identify XSS vectors.",
        features: [
            "Real-time sink monitoring",
            "Source-to-sink tracing",
            "Unsafe API detection",
            "Prototype pollution tracking",
            "Custom sink definitions",
            "Execution context logging",
        ],
        category: "TRACKING",
        price: 27.99,
        icon: "🎯",
        color: "#ff3333",
        compatibility: ["chrome", "edge"],
        version: "1.6.0",
    },
    {
        id: "7",
        slug: "smart-diff-engine",
        name: "Smart Diff Engine",
        tagline: "Intelligent Response Comparison",
        description: "Advanced diffing tool that intelligently compares responses. Filters noise and highlights security-relevant differences.",
        features: [
            "Semantic diff analysis",
            "Noise filtering",
            "Security-focused highlighting",
            "Multi-response comparison",
            "Pattern-based grouping",
            "Export capabilities",
        ],
        category: "ANALYSIS",
        price: 24.99,
        icon: "🔄",
        color: "#00ffff",
        compatibility: ["chrome", "edge"],
        version: "1.4.0",
    },
    {
        id: "8",
        slug: "request-mutator-lab",
        name: "Request Mutator Lab",
        tagline: "Request Manipulation Workshop",
        description: "Interactive workspace for request manipulation and fuzzing. Test hypotheses quickly with an intuitive interface.",
        features: [
            "Visual request editor",
            "Parameter fuzzing",
            "Header manipulation",
            "Cookie testing",
            "Sequence recording",
            "Macro support",
        ],
        category: "ANALYSIS",
        price: 32.99,
        icon: "🧪",
        color: "#8b5cf6",
        compatibility: ["chrome", "edge"],
        version: "2.2.0",
    },
    {
        id: "9",
        slug: "hunters-second-brain",
        name: "Hunter's Second Brain",
        tagline: "Knowledge Management for Hunters",
        description: "Personal knowledge base designed for bug bounty hunters. Link findings, track patterns, and build your hunting playbook.",
        features: [
            "Structured note-taking",
            "Finding correlation",
            "Technique library",
            "Target profiles",
            "Search & filters",
            "Markdown support",
        ],
        category: "UTILITIES",
        price: 29.99,
        icon: "🧠",
        color: "#00ff41",
        compatibility: ["chrome", "edge"],
        version: "1.7.0",
    },
    {
        id: "10",
        slug: "tech-stack-profiler",
        name: "Tech Stack Deep Profiler",
        tagline: "Comprehensive Technology Detection",
        description: "Goes beyond Wappalyzer with deep technology fingerprinting. Identifies frameworks, versions, and potential vulnerabilities.",
        features: [
            "Deep tech fingerprinting",
            "Version detection",
            "CVE correlation",
            "Framework analysis",
            "CDN/WAF detection",
            "Historical tracking",
        ],
        category: "RECON",
        price: 26.99,
        icon: "🔍",
        color: "#ff6a00",
        compatibility: ["chrome", "edge"],
        version: "1.9.0",
    },
    {
        id: "11",
        slug: "api-schema-reconstructor",
        name: "API Schema Reconstructor",
        tagline: "Automatic API Documentation",
        description: "Reconstructs API schemas from observed traffic. Builds OpenAPI specs and identifies undocumented endpoints.",
        features: [
            "Automatic schema generation",
            "OpenAPI spec export",
            "Endpoint discovery",
            "Parameter inference",
            "Authentication mapping",
            "GraphQL support",
        ],
        category: "RECON",
        price: 34.99,
        icon: "📋",
        color: "#00ffff",
        compatibility: ["chrome", "edge"],
        version: "2.0.0",
        featured: true,
    },
    {
        id: "12",
        slug: "blind-interaction-tracker",
        name: "Blind Interaction Tracker (BIT)",
        tagline: "Out-of-Band Interaction Monitoring",
        description: "Tracks blind/out-of-band interactions with your collaborator server. Perfect for blind XSS, SSRF, and XXE testing.",
        features: [
            "OOB interaction tracking",
            "DNS/HTTP callback monitoring",
            "Payload management",
            "Correlation engine",
            "Alert notifications",
            "Integration with Burp Collaborator",
        ],
        category: "TRACKING",
        price: 32.99,
        icon: "👁️",
        color: "#8b5cf6",
        compatibility: ["chrome", "edge"],
        version: "1.5.0",
    },
    {
        id: "13",
        slug: "access-control-matrix",
        name: "Access Control Matrix Builder",
        tagline: "Permission Mapping & Analysis",
        description: "Automatically maps access control matrices across roles. Identifies IDOR, privilege escalation, and authorization bugs.",
        features: [
            "Role-based matrix building",
            "IDOR detection",
            "Privilege gap analysis",
            "Endpoint authorization map",
            "Comparison views",
            "Report generation",
        ],
        category: "ANALYSIS",
        price: 29.99,
        icon: "🗝️",
        color: "#facc15",
        compatibility: ["chrome", "edge"],
        version: "1.3.0",
    },
    {
        id: "14",
        slug: "report-generator-pro",
        name: "Report Generator Pro",
        tagline: "Professional Report Automation",
        description: "Generate professional bug bounty reports in seconds. Templates, screenshots, and proof-of-concept formatting included.",
        features: [
            "Template library",
            "Screenshot annotation",
            "PoC formatting",
            "CVSS calculator",
            "Platform integrations",
            "PDF/Markdown export",
        ],
        category: "REPORTING",
        price: 24.99,
        icon: "📝",
        color: "#00ff41",
        compatibility: ["chrome", "edge"],
        version: "2.1.0",
    },
    {
        id: "15",
        slug: "websocket-analyzer",
        name: "WebSocket & Real-Time Traffic Analyzer",
        tagline: "Real-Time Protocol Analysis",
        description: "Deep analysis of WebSocket, SSE, and real-time traffic. Decode, intercept, and manipulate bidirectional communications.",
        features: [
            "WebSocket interception",
            "SSE monitoring",
            "Message decoding",
            "Traffic manipulation",
            "Protocol detection",
            "Replay capabilities",
        ],
        category: "ANALYSIS",
        price: 29.99,
        icon: "🔌",
        color: "#ff3333",
        compatibility: ["chrome", "edge"],
        version: "1.8.0",
    },
    {
        id: "16",
        slug: "recon-aggregator",
        name: "Recon Aggregator & Auto-Correlator",
        tagline: "Intelligence Correlation Engine",
        description: "Aggregates data from all your recon tools and automatically correlates findings. Build a complete picture of your target.",
        features: [
            "Multi-tool aggregation",
            "Auto-correlation engine",
            "Attack surface mapping",
            "Finding prioritization",
            "Trend analysis",
            "Dashboard views",
        ],
        category: "RECON",
        price: 34.99,
        icon: "🎛️",
        color: "#8b5cf6",
        compatibility: ["chrome", "edge"],
        version: "2.0.0",
    },
    {
        id: "17",
        slug: "workflow-orchestrator",
        name: "Workflow Orchestrator & Hotkey Commander",
        tagline: "Automation & Efficiency Suite",
        description: "Automate your hunting workflows with custom hotkeys and macros. Chain tools together for maximum efficiency.",
        features: [
            "Custom hotkey mapping",
            "Workflow automation",
            "Macro recording",
            "Tool chaining",
            "Quick actions",
            "Productivity metrics",
        ],
        category: "AUTOMATION",
        price: 27.99,
        icon: "⌨️",
        color: "#00ffff",
        compatibility: ["chrome", "edge"],
        version: "1.6.0",
    },
];

export const BUNDLES = [
    {
        id: "starter",
        slug: "starter-pack",
        name: "Starter Pack",
        description: "Essential tools to kickstart your bug bounty journey",
        extensions: ["js-recon-radar", "paramhawk", "scope-guardian"],
        originalPrice: 74.97,
        price: 59.99,
        savings: 20,
        color: "cyan",
        popular: false,
    },
    {
        id: "pro",
        slug: "pro-hunter",
        name: "Pro Hunter Bundle",
        description: "Complete toolkit for serious bug bounty professionals",
        extensions: [
            "js-recon-radar",
            "paramhawk",
            "authflow-visualizer",
            "response-anomaly-detector",
            "dom-sink-tracker",
            "smart-diff-engine",
            "request-mutator-lab",
            "tech-stack-profiler",
        ],
        originalPrice: 239.92,
        price: 149.99,
        savings: 38,
        color: "purple",
        popular: true,
    },
    {
        id: "elite",
        slug: "elite-arsenal",
        name: "Elite Arsenal",
        description: "The complete HexStrike collection. Every tool, unlimited power.",
        extensions: EXTENSIONS.map((e) => e.slug),
        originalPrice: 497.83,
        price: 299.99,
        savings: 40,
        color: "matrix",
        popular: false,
    },
];

export const TESTIMONIALS = [
    {
        id: 1,
        name: "Alex Chen",
        handle: "@alex_security",
        avatar: "AC",
        role: "Security Researcher",
        company: "HackerOne Top 50",
        quote: "JS Recon Radar found 12 hidden endpoints in my first hour. This is exactly what I needed to compete at the top level.",
        rating: 5,
    },
    {
        id: 2,
        name: "Sarah Mitchell",
        handle: "@sarahacks",
        avatar: "SM",
        role: "Bug Bounty Hunter",
        company: "Synack Red Team",
        quote: "The AuthFlow Visualizer changed how I approach auth testing. I've found 3 critical IDORs that I would have missed before.",
        rating: 5,
    },
    {
        id: 3,
        name: "David Park",
        handle: "@d_park_sec",
        avatar: "DP",
        role: "Penetration Tester",
        company: "Independent",
        quote: "ParamHawk's cross-page tracking is incredible. It correlates parameters I never would have connected manually.",
        rating: 5,
    },
    {
        id: 4,
        name: "Maria Garcia",
        handle: "@mgarcia_bb",
        avatar: "MG",
        role: "Security Consultant",
        company: "Big Four",
        quote: "The Pro Hunter Bundle paid for itself in my first week. These tools are what separates amateurs from pros.",
        rating: 5,
    },
    {
        id: 5,
        name: "James Wilson",
        handle: "@jwilson_hunter",
        avatar: "JW",
        role: "Full-time Hunter",
        company: "Bugcrowd MVP",
        quote: "I've tried every browser extension out there. HexStrike is in a completely different league. Worth every penny.",
        rating: 5,
    },
    {
        id: 6,
        name: "Lisa Zhang",
        handle: "@lzhang_security",
        avatar: "LZ",
        role: "AppSec Engineer",
        company: "Fortune 500",
        quote: "Using the Elite Arsenal for internal testing. Found more issues in a week than our previous tools found in months.",
        rating: 5,
    },
];

export const FEATURES = [
    {
        icon: "Zap",
        title: "Real-Time Analysis",
        description: "All extensions work in real-time, analyzing traffic as you browse. No manual scanning required.",
    },
    {
        icon: "Shield",
        title: "Privacy Focused",
        description: "Your data never leaves your browser. All processing happens locally with zero external calls.",
    },
    {
        icon: "Layers",
        title: "Deep Integration",
        description: "Extensions work together seamlessly, sharing context and correlating findings automatically.",
    },
    {
        icon: "Download",
        title: "One-Click Export",
        description: "Export findings to Burp, ZAP, or your favorite format with a single click.",
    },
    {
        icon: "RefreshCw",
        title: "Auto Updates",
        description: "Receive automatic updates with new features and detection capabilities.",
    },
    {
        icon: "HeadphonesIcon",
        title: "Priority Support",
        description: "Get help when you need it from security researchers who understand your workflow.",
    },
];

export const STATS = [
    { label: "Active Users", value: "5,000+", icon: "Users" },
    { label: "Bugs Found", value: "$2.5M+", icon: "Bug" },
    { label: "Extensions", value: "17", icon: "Puzzle" },
    { label: "Updates/Month", value: "12+", icon: "Rocket" },
];

export const FAQ = [
    {
        question: "Are the extensions compatible with other security tools?",
        answer: "Absolutely. All HexStrike extensions are designed to complement tools like Burp Suite, ZAP, and other proxies. Many include direct export capabilities to these platforms.",
    },
    {
        question: "Do the extensions work on all websites?",
        answer: "Yes, the extensions work on any website you visit. Some features may be limited on sites with strict CSP policies, but core functionality remains intact.",
    },
    {
        question: "How do updates work?",
        answer: "Updates are delivered automatically through the Chrome/Edge extension store. You'll always have the latest features and detection capabilities without any manual intervention.",
    },
    {
        question: "Is my data sent to external servers?",
        answer: "No. All processing happens locally in your browser. We take privacy seriously - your reconnaissance data, findings, and browsing habits are never transmitted anywhere.",
    },
    {
        question: "Can I use extensions on multiple devices?",
        answer: "Yes! Each license includes activation for up to 3 devices. Need more? Contact us for team licensing options.",
    },
    {
        question: "What's your refund policy?",
        answer: "We offer a 30-day money-back guarantee. If the extensions don't improve your hunting workflow, we'll refund you - no questions asked.",
    },
];
